version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - news-network
    ports:
      - '27017:27017'

  app:
    build:
      context: . # This points to the directory containing your Dockerfile
      dockerfile: Dockerfile # Make sure the Dockerfile name is correct
    container_name: news-aggregator-app
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/news-aggregator?authSource=admin
    networks:
      - news-network
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

networks:
  news-network:
    driver: bridge
